# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get secret from base64
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run:
        echo $env:BOT_TOKEN
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Run style checker
      run: mvn -B verify checkstyle:checkstyle -DskipTests
    - name: Run pmd analysis
      run: mvn pmd:pmd -DskipTests
    - name: create style report
      uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/checkstyle-result.xml'
    - name: create pmd report
      uses: jwgmeligmeyling/pmd-github-action@master
      with:
        path: '**/pmd.xml'
    - name: Move report
      run: |
        mv -f target/site/checkstyle.html reports
        mv -f target/site/checkstyle.rss reports
        mv -f target/site/pmd.html reports
    - name: Commit report
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: github-actions[bot]@users.noreply.github.com
        message: 'Autogenerated reports for style and source code analysis'
        add: 'reports/*'